export const financeIntegrationFlows = [
  {
    from: "site_reporting",
    to: "project_cost_control",
    label: "Remontees terrain vers couts chantier",
    payloads: ["rapports journalier", "personnel present", "incidents", "constats de cout"],
    interactionPoints: ["rapport chantier", "revue hebdomadaire"],
  },
  {
    from: "project_cost_control",
    to: "budgeting",
    label: "Couts reels vers atterrissage budgetaire",
    payloads: ["couts main-d'oeuvre", "materiel", "marge projet", "variance chantier"],
    interactionPoints: ["revision budget chantier", "comite projet"],
  },
  {
    from: "payroll_planning",
    to: "budgeting",
    label: "Masse salariale vers budget",
    payloads: ["prevision paie", "charges", "absences impactantes"],
    interactionPoints: ["prevision mensuelle", "reforecasts"],
  },
  {
    from: "payroll_planning",
    to: "treasury",
    label: "Runs de paie vers cash planning",
    payloads: ["date de paie", "net a payer", "charges sociales"],
    interactionPoints: ["plan de tresorerie", "prevision hebdomadaire"],
  },
  {
    from: "payment_delays_btp",
    to: "treasury",
    label: "Retards BTP vers liquidite",
    payloads: ["impayes clients", "echeanciers", "decomptes", "delais fournisseurs"],
    interactionPoints: ["priorisation des reglements", "plan de recouvrement"],
  },
  {
    from: "treasury",
    to: "accounting_reporting",
    label: "Flux reels vers comptabilite",
    payloads: ["paiements", "rapprochements", "soldes comptes"],
    interactionPoints: ["cloture", "rapprochement bancaire"],
  },
  {
    from: "accounting_reporting",
    to: "analytics_decision",
    label: "Comptabilite vers pilotage",
    payloads: ["etat resultat", "cash-flow", "position fiscale", "ecarts de production"],
    interactionPoints: ["revue DAF", "comite de direction"],
  },
  {
    from: "budgeting",
    to: "analytics_decision",
    label: "Budgets vers arbitrages",
    payloads: ["versions budget", "ecarts reel/prevision", "alertes de depassement"],
    interactionPoints: ["arbitrage budgetaire", "scenario planning"],
  },
  {
    from: "project_cost_control",
    to: "analytics_decision",
    label: "Marge chantier vers decisions",
    payloads: ["marge par projet", "cout final estime", "avance chantier"],
    interactionPoints: ["comite portefeuille", "revue marge"],
  },
  {
    from: "audit_trail",
    to: "analytics_decision",
    label: "Historique vers analyse causale",
    payloads: ["timeline", "modifications critiques", "evenements de correction"],
    interactionPoints: ["post-mortem financier", "analyse d'ecart"],
  },
  {
    from: "all",
    to: "audit_trail",
    label: "Traçabilite transverse",
    payloads: ["creation", "mise a jour", "validation", "paiement", "rapport terrain"],
    interactionPoints: ["audit interne", "controle operationnel"],
  },
];
