"""Initial schema

Revision ID: 68bdcda40e83
Revises: 
Create Date: 2026-03-29 05:38:01.060325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bdcda40e83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=128), nullable=False),
    sa.Column('tax_number', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("onboarding_status IN ('pending', 'approved', 'rejected')", name='ck_companies_onboarding_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('tax_number')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("default_language IN ('fr', 'en')", name='ck_company_settings_default_language'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_company_settings_company_id')
    )
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_settings_company_id'), ['company_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('min_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_inventory_items_company_sku')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_company_id'), ['company_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'on_hold', 'completed', 'cancelled')", name='ck_projects_status'),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_projects_progress_percent'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_projects_company_code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_company_id'), ['company_id'], unique=False)

    op.create_table('public_tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contracting_authority', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_estimate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('submission_deadline', sa.Date(), nullable=True),
    sa.Column('dao_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'monitoring', 'preparing', 'submitted', 'awarded', 'lost', 'cancelled')", name='ck_public_tenders_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'reference', name='uq_public_tenders_company_reference')
    )
    with op.batch_alter_table('public_tenders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_tenders_company_id'), ['company_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_roles_company_code')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_company_id'), ['company_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('user_type', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("preferred_language IN ('fr', 'en')", name='ck_users_preferred_language'),
    sa.CheckConstraint("user_type IN ('super_admin', 'company_admin', 'employee', 'external_controller', 'job_seeker')", name='ck_users_user_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_users_company_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)

    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('desired_position', sa.String(length=150), nullable=True),
    sa.Column('skills_summary', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.String(length=30), nullable=False),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("availability_status IN ('immediate', 'short_notice', 'not_available')", name='ck_candidate_profiles_availability_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('private', 'group')", name='ck_chat_conversations_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_created_by_user_id'), ['created_by_user_id'], unique=False)

    op.create_table('finance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("entry_type IN ('expense', 'revenue')", name='ck_finance_entries_type'),
    sa.CheckConstraint('amount > 0', name='ck_finance_entries_amount_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_entries_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_entries_recorded_by_user_id'), ['recorded_by_user_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'sent', 'partially_paid', 'paid', 'overdue', 'cancelled')", name='ck_invoices_status'),
    sa.CheckConstraint('amount_paid >= 0', name='ck_invoices_amount_paid_non_negative'),
    sa.CheckConstraint('amount_total > 0', name='ck_invoices_amount_total_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'invoice_number', name='uq_invoices_company_invoice_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_project_id'), ['project_id'], unique=False)

    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'published', 'closed')", name='ck_job_offers_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_offers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_offers_published_by_user_id'), ['published_by_user_id'], unique=False)

    op.create_table('project_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'project_id', 'report_date', name='uq_project_reports_company_project_date')
    )
    with op.batch_alter_table('project_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_reports_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reports_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reports_project_id'), ['project_id'], unique=False)

    op.create_table('project_stock_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_allocated > 0', name='ck_project_stock_allocations_quantity_positive'),
    sa.ForeignKeyConstraint(['allocated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_stock_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_stock_allocations_allocated_by_user_id'), ['allocated_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stock_allocations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stock_allocations_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stock_allocations_project_id'), ['project_id'], unique=False)

    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name='ck_project_tasks_priority'),
    sa.CheckConstraint("status IN ('todo', 'in_progress', 'blocked', 'done')", name='ck_project_tasks_status'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tasks_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('stock_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("location_type IN ('warehouse', 'site')", name='ck_stock_locations_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_stock_locations_company_code')
    )
    with op.batch_alter_table('stock_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_locations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_locations_project_id'), ['project_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('supervisor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'project_id', 'name', name='uq_teams_company_project_name')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_supervisor_user_id'), ['supervisor_user_id'], unique=False)

    op.create_table('tender_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['public_tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tender_checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_checklist_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_checklist_items_tender_id'), ['tender_id'], unique=False)

    op.create_table('tender_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submission_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dao_package_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'under_review', 'awarded', 'lost', 'cancelled')", name='ck_tender_submissions_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['public_tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'tender_id', name='uq_tender_submissions_company_tender')
    )
    with op.batch_alter_table('tender_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_submissions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_submissions_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_submissions_tender_id'), ['tender_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'company_id', name='uq_user_roles_user_role_company')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("call_type IN ('audio', 'video')", name='ck_call_sessions_type'),
    sa.CheckConstraint("status IN ('initiated', 'ringing', 'active', 'ended', 'missed', 'rejected')", name='ck_call_sessions_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_sessions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sessions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sessions_initiated_by_user_id'), ['initiated_by_user_id'], unique=False)

    op.create_table('candidate_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('match_score >= 0 AND match_score <= 100', name='ck_candidate_matches_score'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'job_offer_id', 'candidate_id', name='uq_candidate_matches_company_offer_candidate')
    )
    with op.batch_alter_table('candidate_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_matches_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_matches_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_matches_job_offer_id'), ['job_offer_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("message_type IN ('text', 'image', 'file', 'system')", name='ck_chat_messages_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sender_user_id'), ['sender_user_id'], unique=False)

    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'conversation_id', 'user_id', name='uq_chat_participants_company_conversation_user')
    )
    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_participants_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_participants_user_id'), ['user_id'], unique=False)

    op.create_table('invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_invoice_payments_amount_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_payments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_payments_received_by_user_id'), ['received_by_user_id'], unique=False)

    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'screening', 'interview', 'shortlisted', 'rejected', 'hired')", name='ck_job_applications_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_offer_id', 'candidate_id', name='uq_job_applications_offer_candidate')
    )
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_applications_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_job_offer_id'), ['job_offer_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("movement_type IN ('in', 'out', 'transfer', 'adjustment', 'allocation')", name='ck_stock_movements_type'),
    sa.CheckConstraint('quantity > 0', name='ck_stock_movements_quantity_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['stock_locations.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['stock_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_from_location_id'), ['from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_performed_by_user_id'), ['performed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_to_location_id'), ['to_location_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_on_team', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'team_id', 'user_id', name='uq_team_members_company_team_user')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('call_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'call_session_id', 'user_id', name='uq_call_participants_company_call_user')
    )
    with op.batch_alter_table('call_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_participants_call_session_id'), ['call_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_participants_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_participants_user_id'), ['user_id'], unique=False)

    op.create_table('chat_message_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'message_id', 'user_id', name='uq_chat_message_reads_company_message_user')
    )
    with op.batch_alter_table('chat_message_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_reads_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_reads_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_reads_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_reads_message_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_reads_company_id'))

    op.drop_table('chat_message_reads')
    with op.batch_alter_table('call_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_call_participants_company_id'))
        batch_op.drop_index(batch_op.f('ix_call_participants_call_session_id'))

    op.drop_table('call_participants')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_company_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_to_location_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_performed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_from_location_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_company_id'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_applications_job_offer_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_company_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_candidate_id'))

    op.drop_table('job_applications')
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payments_received_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_payments_company_id'))

    op.drop_table('invoice_payments')
    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_participants_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_chat_participants_company_id'))

    op.drop_table('chat_participants')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_company_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('candidate_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_matches_job_offer_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_matches_company_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_matches_candidate_id'))

    op.drop_table('candidate_matches')
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_sessions_initiated_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_call_sessions_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_call_sessions_company_id'))

    op.drop_table('call_sessions')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_company_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('tender_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_submissions_tender_id'))
        batch_op.drop_index(batch_op.f('ix_tender_submissions_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_tender_submissions_company_id'))

    op.drop_table('tender_submissions')
    with op.batch_alter_table('tender_checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_checklist_items_tender_id'))
        batch_op.drop_index(batch_op.f('ix_tender_checklist_items_company_id'))

    op.drop_table('tender_checklist_items')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_supervisor_user_id'))
        batch_op.drop_index(batch_op.f('ix_teams_project_id'))
        batch_op.drop_index(batch_op.f('ix_teams_company_id'))

    op.drop_table('teams')
    with op.batch_alter_table('stock_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_locations_project_id'))
        batch_op.drop_index(batch_op.f('ix_stock_locations_company_id'))

    op.drop_table('stock_locations')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_company_id'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_assigned_to_user_id'))

    op.drop_table('project_tasks')
    with op.batch_alter_table('project_stock_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_stock_allocations_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_stock_allocations_item_id'))
        batch_op.drop_index(batch_op.f('ix_project_stock_allocations_company_id'))
        batch_op.drop_index(batch_op.f('ix_project_stock_allocations_allocated_by_user_id'))

    op.drop_table('project_stock_allocations')
    with op.batch_alter_table('project_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_reports_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_reports_company_id'))
        batch_op.drop_index(batch_op.f('ix_project_reports_author_user_id'))

    op.drop_table('project_reports')
    with op.batch_alter_table('job_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_offers_published_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_offers_company_id'))

    op.drop_table('job_offers')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_project_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_company_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('finance_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_entries_recorded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_finance_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_finance_entries_company_id'))

    op.drop_table('finance_entries')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_company_id'))

    op.drop_table('chat_conversations')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_user_id'))

    op.drop_table('candidate_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_company_id'))

    op.drop_table('roles')
    with op.batch_alter_table('public_tenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_tenders_company_id'))

    op.drop_table('public_tenders')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_company_id'))

    op.drop_table('projects')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_company_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_settings_company_id'))

    op.drop_table('company_settings')
    op.drop_table('permissions')
    op.drop_table('companies')
    # ### end Alembic commands ###
